name: Deploy Firebase App Hosting

on:
  push:
    branches: [ "main" ]   # 如果你的默认分支不是 main，这里改成对应的名字

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@latest

      - name: Authenticate with Service Account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Deploy App Hosting
        run: |
          firebase --project "studio-1269295870-5fde0" deploy --only apphosting --non-interactive
