name: Deploy Firebase App Hosting

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@latest

      - name: Write service account key
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/gcp-key.json

      - name: Deploy App Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.HOME }}/gcp-key.json
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
        run: |
          firebase --project "$FIREBASE_PROJECT_ID" deploy --only apphosting
